#!/bin/sh

if [[ -e "$BSPWM_STATE" ]] ; then
   #pgrep polybar && pkill -SIGNTERM polybar
   #pgrep sxhkd && pkill -SIGTERM sxhkd
   bspc wm --load-state "$BSPWM_STATE" && rm "$BSPWM_STATE"
fi

[[ -z "$(pidof sxhkd)" ]] && sxhkd -c $XDG_CONFIG_HOME/sxhkd/sxhkdrc &

# sed captures all non digit characters
DISP_X="$(xrandr -q | head -1 | awk -F' ' '{print $8}' | sed 's/[^0-9]//g')"
DISP_Y="$(xrandr -q | head -1 | awk -F' ' '{print $10}' | sed 's/[^0-9]//g')"

bspc config split_ratio             0.5
# cleanup needed
bspc config borderless_monocle      true
bspc config gapless_monocle         true
bspc config focus_by_distance       true
bspc config history_aware_focus     true
bspc config focus_follows_pointer   true
bspc config center_pseudo_tiled     true
bspc config border_width            "$(echo "scale=0;2.5*$(echo $DISP_X)/$(echo $DISP_Y)" | bc)"
bspc config window_gap		         16
bspc config top_padding             $(($DISP_Y / 100 * 4))
bspc config left_padding            $(($DISP_X * 0))
bspc config right_padding           $(($DISP_X * 0))
bspc config bottom_padding          $(($DISP_Y / 100 * 3))
bspc config normal_border_color     "#060606"
bspc config focused_border_color    "#51C4D4"
bspc config presel_feedback_color   "#62c9d8"

monitors="$(xrandr --listactivemonitors | tail -n +2 | awk -F' ' '{ print $4 }')"
case "$(echo "$monitors" | wc -l)" in
   "2")
      bspc monitor "$(echo "$monitors" | head -n 1)" -d I II III IV V 
      bspc monitor "$(echo "$monitors" | tail -n 1)" -d VI VII VII IX X
      ;;
   *)
      bspc monitor "$(echo "$monitors" | head -n 1)" -d I II III IV V VI VII VIII IX X
      ;;
esac

bspc rule -r *:*
bspc rule -a feh state=floating follow=on
bspc rule -a telegram-desktop state=floating follow=on
bspc rule -a rofi state=floating follow=on
bspc rule -a Zathura state=tiled
bspc rule -a vivaldi-stable desktop=^1

[[ -z "$(pidof polybar)" ]] && $XDG_CONFIG_HOME/polybar/launch.sh
