#!/bin/sh

if [ -e "$BSPWM_STATE" ] ; then
   pkill -x sxhkd
   bspc wm --load-state "$BSPWM_STATE"
   rm "$BSPWM_STATE"
fi

sxhkd -c $XDG_CONFIG_HOME/sxhkd/sxhkdrc &

bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_by_distance    true
bspc config history_aware_focus  true
bspc config focus_follows_pointer true
bspc config center_pseudo_tiled  true
bspc config border_width	7
bspc config window_gap		24
bspc config top_padding         38
bspc config left_padding        38
bspc config right_padding       38
bspc config bottom_padding      38
bspc config normal_border_color "#131313"
bspc config focused_border_color "#51C4D4"
bspc config presel_feedback_color "#51c4d4"

monitors="$(xrandr --listactivemonitors | tail -n +2 | awk -F' ' '{ print $4 }')"
case "$(echo "$monitors" | wc -l)" in
   "2")
      bspc monitor "$(echo "$monitors" | head -n 1)" -d I II III IV V 
      bspc monitor "$(echo "$monitors" | tail -n 1)" -d VI VII VII IX X
      ;;
   *)
      bspc monitor "$(echo "$monitors" | head -n 1)" -d I II III IV V VI VII VIII IX X
      ;;
esac

bspc rule -a feh state=floating follow=on
bspc rule -a telegram-desktop state=floating follow=on
bspc rule -a rofi state=floating follow=on
bspc rule -a Zathura state=floating
bspc rule -a vivaldi-stable desktop=^1

# Xflux (for night-time coding)
xflux -l 45.438158 -g 10.993742 &

# soon replace w/ polybar
if [ $(pgrep 'yabar') ]; then
    pgrep 'yabar' | xargs kill -s 15
fi

sleep 1 && yabar &
