#!/bin/env sh
if [ -e "$BSPWM_STATE" ] ; then
    #pgrep polybar && pkill -SIGNTERM polybar
    #pgrep sxhkd && pkill -SIGTERM sxhkd
    bspc wm --load-state "$BSPWM_STATE" && rm "$BSPWM_STATE"

    killall -q compton
    while pgrep -x compton >/dev/null; do sleep 1; done
    compton --config $XDG_CONFIG_HOME/compton/compton.conf --daemon
else
    termite &
    xautolock -locknow
fi

[ -z "$(pidof sxhkd)" ] && sxhkd -c $XDG_CONFIG_HOME/sxhkd/sxhkdrc &

# sed captures all non digit characters
DISP_X="$(xrandr -q | awk -F' ' '{ if (NR == 1) print $8}' | sed 's/[^0-9]//g')"
DISP_Y="$(xrandr -q | awk -F' ' '{ if (NR == 1) print $10}' | sed 's/[^0-9]//g')"
border=$(bc <<< "scale=0;2.8*$DISP_X/$DISP_Y")

bspc config split_ratio             0.5
bspc config borderless_monocle      true
bspc config gapless_monocle         true
bspc config focus_by_distance       true
bspc config history_aware_focus     true
bspc config focus_follows_pointer   true
bspc config center_pseudo_tiled     false
bspc config border_width            $border
bspc config window_gap              $(bc <<< "scale=0;4.5*$border")
bspc config top_padding             $(($DISP_Y / 100 * 4))
bspc config left_padding            $(($DISP_X * 0))
bspc config right_padding           $(($DISP_X * 0))
bspc config bottom_padding          $(($DISP_Y / 100))
bspc config normal_border_color     "#7F7F7F"
bspc config focused_border_color    "#F4F4F4"
bspc config presel_feedback_color   "#B2B2B2"

unset border

monitors="$(xrandr --listactivemonitors | awk -F' ' '{ if (NR > 1) print $NF }')"
case "$(echo "$monitors" | wc -l)" in
    "2")
        bspc monitor "$(echo "$monitors" | head -n 1)" -d I II III IV V 
        bspc monitor "$(echo "$monitors" | tail -n 1)" -d VI VII VII IX X
        ;;
    *)
        bspc monitor "$(echo "$monitors" | head -n 1)" -d I II III IV V VI VII VIII IX X
        ;;
esac

bspc rule -r *:*
bspc rule -a feh state=floating follow=on
bspc rule -a telegram-desktop state=floating follow=on
bspc rule -a rofi state=floating follow=on
bspc rule -a Zathura state=tiled
bspc rule -a vivaldi-stable desktop=^1

[ -z "$(pidof polybar)" ] && $XDG_CONFIG_HOME/polybar/launch.sh
